# Development PostgreSQL with pgvector extension
# Usage:
#   docker compose -f compose.dev.yaml up -d
#   docker compose -f compose.dev.yaml down
#   docker compose -f compose.dev.yaml logs -f db

name: "tavern-dev"

services:
  db:
    image: pgvector/pgvector:pg18-trixie
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/18
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  postgres-data:
