# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

Minitest::TestTask.create do |t|
  # Ensure SimpleCov (loaded by test_helper) installs its at_exit handler
  # before Minitest's autorun, otherwise coverage will be reported before the
  # test suite executes.
  t.framework = %(require_relative "./test/test_helper")
end

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[test rubocop]
