# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

Minitest::TestTask.create do |t|
  # Ensure SimpleCov (loaded by test_helper) installs its at_exit handler
  # before Minitest's autorun, otherwise coverage will be reported before the
  # test suite executes.
  t.framework = %(require_relative "./test/test_helper")
end

Minitest::TestTask.create(:guardrails) do |t|
  t.framework = %(require_relative "./test/test_helper")
  t.test_globs = [
    "test/characterization/wave4_*_contract_test.rb",
    "test/characterization/st_*_test.rb",
  ]
end

Minitest::TestTask.create(:conformance) do |t|
  t.framework = %(require_relative "./test/test_helper")
  t.test_globs = [
    "test/conformance/**/*_test.rb",
  ]
end

Minitest::TestTask.create(:integration) do |t|
  t.framework = %(require_relative "./test/test_helper")
  t.test_globs = [
    "test/integration/**/*_test.rb",
  ]
end

Minitest::TestTask.create(:risuai) do |t|
  t.framework = %(require_relative "./test/test_helper")
  t.test_globs = [
    "test/characterization/risuai_*_test.rb",
    "test/integration/risuai_*_test.rb",
  ]
end

namespace :test do
  # Alias to align with the main app's `rake test:*` conventions.
  task guardrails: :guardrails
  task conformance: :conformance
  task integration: :integration
  task risuai: :risuai
  task wave5: %i[guardrails conformance integration risuai]
end

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[test rubocop]
