WITH t_0_OrwellBooks AS (SELECT
  ArgMin(JSON_EXTRACT(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell')), '$[' || x_7.value || ']'), x_7.value, null) AS logica_value
FROM
  JSON_EACH((select json_group_array(n) from (with recursive t as(select 0 as n union all select n + 1 as n from t where n + 1 < JSON_ARRAY_LENGTH(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell')))) select n from t) where n < JSON_ARRAY_LENGTH(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell'))))) as x_7
WHERE
  (JSON_EXTRACT(JSON_EXTRACT(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell')), '$[' || x_7.value || ']'), "$.author") = 'George Orwell')),
t_2_NameAndAuthor AS (SELECT
  JSON_GROUP_ARRAY(((((((((JSON_EXTRACT(JSON_EXTRACT(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell')), '$[' || x_28.value || ']'), "$.book_name")) || (' and '))) || (JSON_EXTRACT(JSON_EXTRACT(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell')), '$[' || x_29.value || ']'), "$.book_name")))) || (' by '))) || (JSON_EXTRACT(JSON_EXTRACT(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell')), '$[' || x_28.value || ']'), "$.author")))) AS logica_value
FROM
  JSON_EACH((select json_group_array(n) from (with recursive t as(select 0 as n union all select n + 1 as n from t where n + 1 < JSON_ARRAY_LENGTH(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell')))) select n from t) where n < JSON_ARRAY_LENGTH(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell'))))) as x_28, JSON_EACH((select json_group_array(n) from (with recursive t as(select 0 as n union all select n + 1 as n from t where n + 1 < x_28.value) select n from t) where n < x_28.value)) as x_29
WHERE
  (JSON_EXTRACT(JSON_EXTRACT(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell')), '$[' || x_28.value || ']'), "$.author") = JSON_EXTRACT(JSON_EXTRACT(JSON_ARRAY(JSON_OBJECT('book_name', 'The Hobbit', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'The Lord of the Rings', 'author', 'J.R.R. Tolkien'), JSON_OBJECT('book_name', 'Harry Potter and the Philosopher''s Stone', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', 'Harry Potter and the Deathly Hallows', 'author', 'J.K. Rowling'), JSON_OBJECT('book_name', '1984', 'author', 'George Orwell'), JSON_OBJECT('book_name', 'Animal Farm', 'author', 'George Orwell')), '$[' || x_29.value || ']'), "$.author"))),
t_4_A2d AS (SELECT
  ArgMin((SELECT
  ArgMin(JSON_EXTRACT(MagicalEntangle(JSON_OBJECT('arg', x_82.value, 'value', ((((10) * (x_41.value))) + (x_82.value))), x_83.value), "$.value"), JSON_EXTRACT(MagicalEntangle(JSON_OBJECT('arg', x_82.value, 'value', ((((10) * (x_41.value))) + (x_82.value))), x_83.value), "$.arg"), null) AS logica_value
FROM
  JSON_EACH((select json_group_array(n) from (with recursive t as(select 0 as n union all select n + 1 as n from t where n + 1 < 4) select n from t) where n < 4)) as x_82, JSON_EACH(JSON_ARRAY(0)) as x_83), x_41.value, null) AS logica_value
FROM
  JSON_EACH((select json_group_array(n) from (with recursive t as(select 0 as n union all select n + 1 as n from t where n + 1 < 5) select n from t) where n < 5)) as x_41)
SELECT * FROM (
  
    SELECT
      'OrwellBooks' AS col0,
      OrwellBooks.logica_value AS col1
    FROM
      t_0_OrwellBooks AS OrwellBooks UNION ALL
  
    SELECT
      'NameAndAuthor' AS col0,
      NameAndAuthor.logica_value AS col1
    FROM
      t_2_NameAndAuthor AS NameAndAuthor UNION ALL
  
    SELECT
      'FromMatrix' AS col0,
      JSON_ARRAY(JSON_OBJECT('a23', JSON_EXTRACT(JSON_EXTRACT(A2d.logica_value, '$[' || 2 || ']'), '$[' || 3 || ']'), 'a41', JSON_EXTRACT(JSON_EXTRACT(A2d.logica_value, '$[' || 4 || ']'), '$[' || 1 || ']'), 'a11', JSON_EXTRACT(JSON_EXTRACT(A2d.logica_value, '$[' || 1 || ']'), '$[' || 1 || ']'))) AS col1
    FROM
      t_4_A2d AS A2d
) AS UNUSED_TABLE_NAME  ;
